// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoyO2KRZJhr22R83e-qhK5_R8q0geaTo',
    appId: '1:394338459731:web:f954f78474e7ec0934a6a6',
    messagingSenderId: '394338459731',
    projectId: 'eduventure-nodejs8',
    authDomain: 'eduventure-nodejs8.firebaseapp.com',
    storageBucket: 'eduventure-nodejs8.appspot.com',
    measurementId: 'G-K35H2V0SEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tSf1omp8YFjufLp6ImuPo8oywFyALJA',
    appId: '1:394338459731:android:27024fc0b32fe28e34a6a6',
    messagingSenderId: '394338459731',
    projectId: 'eduventure-nodejs8',
    storageBucket: 'eduventure-nodejs8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2LdpWhYZUkQbi2o6LMcH_N9jhluS5IQ',
    appId: '1:394338459731:ios:756ea9953e63978c34a6a6',
    messagingSenderId: '394338459731',
    projectId: 'eduventure-nodejs8',
    storageBucket: 'eduventure-nodejs8.appspot.com',
    iosBundleId: 'com.example.eduventureNodejs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2LdpWhYZUkQbi2o6LMcH_N9jhluS5IQ',
    appId: '1:394338459731:ios:d28bf875fd497ef534a6a6',
    messagingSenderId: '394338459731',
    projectId: 'eduventure-nodejs8',
    storageBucket: 'eduventure-nodejs8.appspot.com',
    iosBundleId: 'com.example.eduventureNodejs.RunnerTests',
  );
}
